# Мархель Сергей
## Группа: БСТ1901
### Problems_1

### Задание 1

In [46]:
def is_triangle(a, b, c):
    if a + b > c and a + c > b and b + c > a:
        return True
    else:
        return False

def get_max_triangle(arr):
    if len(arr) < 3:
        return 0
    arr = sorted(arr, reverse=True)
    sides = arr[:3]
    if is_triangle(sides[0], sides[1], sides[2]):
        return sides[0] + sides[1] + sides[2]
    else:
        return get_max_triangle(arr[1:])


print(get_max_triangle([2,1,2]))
print(get_max_triangle([1,2,1]))
print(get_max_triangle([3,2,3,4]))
print(get_max_triangle([3,6,2,3]))

5
0
10
8


### Задание 2

In [47]:
def highest_comb(L):
    max_length = len(str(max(L)))
    L = map(str, L)
    def sort_key(s):
        return s + s[-1] * (max_length - len(s))

    sorted_list = sorted(L, key=sort_key, reverse=True)
    return ''.join(sorted_list)

highest_comb([50, 9, 2, 1])

'95021'

### Задание 3

In [48]:
import numpy

m = 4
n = 4
massiv = numpy.random.randint(0, 20, size=(m, n))
print("Исходная матрица:\n", massiv)

for i in range(-len(massiv) + 1, len(massiv) + m % n):
    d = numpy.diag(massiv, i)
    d = numpy.sort(d)
    massiv.ravel()[max(i,-massiv.shape[1]*i):max(0,(massiv.shape[1]-i))*massiv.shape[1]:massiv.shape[1]+1] = d

print("Результат:\n",massiv)

Исходная матрица:
 [[ 3 17 14 10]
 [16  6 18 10]
 [ 4 18 11  3]
 [ 8 12 15 18]]
Результат:
 [[ 3  3 10 10]
 [15  6 17 14]
 [ 4 16 11 18]
 [ 8 12 18 18]]
